# Generated by Django 4.2.2 on 2023-07-29 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrict_user', models.BooleanField(blank=True, default=True, null=True)),
                ('customer_stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=40)),
                ('subscription_type', models.CharField(choices=[('monthly', 'monthly'), ('annually', 'annually')], max_length=20)),
                ('status', models.CharField(choices=[('trial', 'trial'), ('active', 'active'), ('canceled', 'canceled')], default='trial', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stripe_pay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
