# Generated by Django 4.2.2 on 2023-07-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmoney',
            name='annaully_boss_mode',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='subscriptionmoney',
            name='annaully_starter',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='subscriptionmoney',
            name='monthly_boss_mode',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='subscriptionmoney',
            name='monthly_starter',
            field=models.CharField(max_length=40),
        ),
    ]
