# Generated by Django 4.2.2 on 2023-07-30 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0004_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stripe_pay', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
