# Generated by Django 4.2.2 on 2023-07-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trail_ends',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
