# Generated by Django 4.2.2 on 2023-07-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_trail_ends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionmoney',
            old_name='annaully_boss_mode',
            new_name='annaully_premium_mode',
        ),
        migrations.RenameField(
            model_name='subscriptionmoney',
            old_name='monthly_boss_mode',
            new_name='monthly_premium_mode',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'starter'), ('premium', 'premium'), ('enterprise', 'enterprise')], max_length=20),
        ),
    ]
