# Generated by Django 4.2.2 on 2023-08-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_subsciption_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subsciption_stripe_id',
            new_name='subscription_stripe_id',
        ),
    ]
