# Generated by Django 3.2 on 2023-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscribeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountSubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Subscription of Users'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionmoney',
            options={'verbose_name_plural': 'Subscription Payment'},
        ),
    ]
