# Generated by Django 3.2 on 2023-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_auto_20230814_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_seat', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Team Member Price',
            },
        ),
    ]
