# Generated by Django 3.2 on 2023-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_subscription_subscription_team_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(blank=True, choices=[('starter', 'starter'), ('premium', 'premium'), ('enterprise', 'enterprise')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(blank=True, choices=[('trial', 'trial'), ('active', 'active'), ('canceled', 'canceled')], default='trial', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('annually', 'annually')], max_length=20, null=True),
        ),
    ]
