# Generated by Django 3.2 on 2023-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_enterpriseplanlist_monthlyplanlist_yearlyplanlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseplanlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='enterpriseplanlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monthlyplanlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyplanlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yearlyplanlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlyplanlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
