# Generated by Django 3.2 on 2023-10-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_auto_20231008_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyplanlist',
            options={'verbose_name_plural': 'Why Monthly'},
        ),
    ]
