# Generated by Django 4.2.2 on 2023-07-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_template', '0003_chatvalueoftemplatemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatTemplateModel',
            new_name='ChatFirstTemplateModel',
        ),
        migrations.RenameModel(
            old_name='ChatFirstStepTemplateModel',
            new_name='ChatSecondStepTemplateModel',
        ),
        migrations.RenameModel(
            old_name='ChatValueOfTemplateModel',
            new_name='ChatThirdValueOfTemplateModel',
        ),
    ]
