# Generated by Django 4.2.2 on 2023-07-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0002_projects_favorite_alter_projects_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='publish',
            new_name='trash',
        ),
    ]
