# Generated by Django 3.2 on 2023-08-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_members', '0017_alter_initialworkshopofuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Template Category',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerTokenGeneratedByOpenAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_generated', models.CharField(max_length=50)),
                ('default_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Per Token By User',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('what_to_generate', models.TextField()),
                ('premium', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='template.Categorie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='TokenGeneratedByOpenAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_generated', models.CharField(max_length=50)),
                ('default_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Token Generated',
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAnswerModelOfUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_template_answers', to=settings.AUTH_USER_MODEL)),
                ('workspace_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_id_of_template_ans', to='team_members.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Template_Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('pre_define_value', models.TextField(blank=True, null=True)),
                ('component', models.CharField(choices=[('text', 'text'), ('textarea', 'textarea'), ('select', 'select'), ('Example', 'Example')], max_length=20)),
                ('type_field', models.CharField(choices=[('string', 'string')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(max_length=100)),
                ('range_of_text', models.PositiveIntegerField()),
                ('maxLength', models.PositiveIntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TemplateIdTemplateField', to='template.template')),
            ],
            options={
                'verbose_name_plural': 'Template Field',
            },
        ),
        migrations.CreateModel(
            name='TempalteSelectFieldOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserIdSelectField', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Template Field Options',
            },
        ),
        migrations.CreateModel(
            name='SingleUserTokenGenerated',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_generated', models.CharField(max_length=450)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TokenGeneratedByUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_answer', models.ManyToManyField(related_name='ProjectTemplateResponse', to='template.TemplateAnswerModelOfUser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserIdProject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
