# Generated by Django 3.2 on 2023-08-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_singleusertokengenerated_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_field',
            name='steps',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
