# Generated by Django 3.2 on 2023-08-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_template_field_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenAiToken',
        ),
    ]
