# Generated by Django 3.2 on 2023-08-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0009_singleusertokengenerated_template_used'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenAiToken',
        ),
    ]
