# Generated by Django 3.2 on 2023-08-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0011_openaitoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenAiToken',
        ),
    ]
