# Generated by Django 3.2 on 2023-08-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0044_openaitoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenAiToken',
        ),
    ]
