# Generated by Django 3.2 on 2023-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0047_generateaudiotospeech_generatedimagebyuser_howtosummarizetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateaudiotospeech',
            name='url_of_video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
