# Generated by Django 3.2 on 2023-09-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0020_alter_teammemberteamnumber_no_of_member'),
        ('template', '0048_generateaudiotospeech_url_of_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimagebyuser',
            name='workspace_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_by_wrk_ins_img_generated', to='team_members.workspace'),
        ),
    ]
