# Generated by Django 3.2 on 2023-09-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0020_alter_teammemberteamnumber_no_of_member'),
        ('template', '0049_generatedimagebyuser_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateaudiotospeech',
            name='minutes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateaudiotospeech',
            name='workspace_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_by_wrk_ins_speech_to_text', to='team_members.workspace'),
        ),
    ]
