# Generated by Django 3.2 on 2023-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0050_auto_20230907_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateaudiotospeech',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
