# Generated by Django 3.2 on 2023-09-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0051_alter_generateaudiotospeech_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateaudiotospeech',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
