# Generated by Django 3.2 on 2023-09-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0055_tempvideodetails_scripts_of_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempvideodetails',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
