# Generated by Django 3.2 on 2024-01-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnsplashPhoto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('blur_hash', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alt_description', models.CharField(max_length=255)),
                ('raw_url', models.URLField()),
                ('full_url', models.URLField()),
                ('regular_url', models.URLField()),
                ('small_url', models.URLField()),
                ('thumb_url', models.URLField()),
                ('small_s3_url', models.URLField()),
                ('self_link', models.URLField()),
                ('html_link', models.URLField()),
                ('download_link', models.URLField()),
                ('download_location_link', models.URLField()),
                ('likes', models.IntegerField()),
                ('liked_by_user', models.BooleanField()),
                ('tagline', models.CharField(max_length=255)),
                ('tagline_url', models.URLField()),
                ('sponsor_id', models.CharField(max_length=50)),
                ('sponsor_updated_at', models.DateTimeField()),
                ('sponsor_username', models.CharField(max_length=255)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsor_twitter_username', models.CharField(max_length=255)),
                ('sponsor_portfolio_url', models.URLField()),
                ('sponsor_bio', models.TextField()),
                ('sponsor_location', models.CharField(max_length=255)),
                ('sponsor_self_link', models.URLField()),
                ('sponsor_html_link', models.URLField()),
                ('sponsor_photos_link', models.URLField()),
                ('sponsor_likes_link', models.URLField()),
                ('sponsor_portfolio_link', models.URLField()),
                ('sponsor_following_link', models.URLField()),
                ('sponsor_followers_link', models.URLField()),
                ('sponsor_profile_image_small', models.URLField()),
                ('sponsor_profile_image_medium', models.URLField()),
                ('sponsor_profile_image_large', models.URLField()),
                ('sponsor_instagram_username', models.CharField(max_length=255)),
                ('sponsor_total_collections', models.IntegerField()),
                ('sponsor_total_likes', models.IntegerField()),
                ('sponsor_total_photos', models.IntegerField()),
                ('sponsor_total_promoted_photos', models.IntegerField()),
                ('sponsor_accepted_tos', models.BooleanField()),
                ('sponsor_for_hire', models.BooleanField()),
                ('sponsor_instagram_username_link', models.URLField()),
                ('sponsor_portfolio_url_link', models.URLField()),
                ('sponsor_twitter_username_link', models.URLField()),
            ],
        ),
    ]
