# Generated by Django 3.2 on 2024-01-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsplashphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
