# Generated by Django 3.2 on 2024-01-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0002_alter_unsplashphoto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('promoted_at', models.DateTimeField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('blur_hash', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alt_description', models.CharField(max_length=255)),
                ('breadcrumbs', models.JSONField(default=list)),
                ('raw_url', models.URLField()),
                ('full_url', models.URLField()),
                ('regular_url', models.URLField()),
                ('small_url', models.URLField()),
                ('thumb_url', models.URLField()),
                ('small_s3_url', models.URLField()),
                ('self_link', models.URLField()),
                ('html_link', models.URLField()),
                ('download_link', models.URLField()),
                ('download_location_link', models.URLField()),
                ('likes', models.IntegerField()),
                ('liked_by_user', models.BooleanField(default=False)),
                ('current_user_collections', models.JSONField(default=list)),
                ('impression_urls', models.JSONField(default=list)),
                ('tagline', models.CharField(max_length=255)),
                ('tagline_url', models.URLField()),
                ('sponsor_id', models.CharField(max_length=255)),
                ('sponsor_updated_at', models.DateTimeField()),
                ('sponsor_username', models.CharField(max_length=255)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsor_bio', models.TextField()),
                ('sponsor_location', models.CharField(max_length=255)),
                ('sponsor_total_collections', models.IntegerField()),
                ('sponsor_total_likes', models.IntegerField()),
                ('sponsor_total_photos', models.IntegerField()),
                ('sponsor_total_promoted_photos', models.IntegerField()),
                ('sponsor_accepted_tos', models.BooleanField(default=True)),
                ('sponsor_instagram_username', models.CharField(max_length=255)),
                ('sponsor_portfolio_url', models.URLField()),
                ('sponsor_twitter_username', models.CharField(max_length=255)),
                ('sponsor_paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UnsplashPhoto',
        ),
    ]
