# Generated by Django 3.2 on 2024-01-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0005_auto_20240115_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='breadcrumbs',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='sponsor_paypal_email',
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_for_hire',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_large_profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_medium_profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_small_profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='alt_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='blur_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='download_location_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='full_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='html_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='impression_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='liked_by_user',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='promoted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='raw_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='regular_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='self_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='small_s3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='small_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_accepted_tos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_instagram_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_portfolio_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_total_collections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_total_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_total_photos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_total_promoted_photos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_twitter_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tagline_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
