# Generated by Django 3.2 on 2024-01-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0006_auto_20240115_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_accepted_tos',
            new_name='accepted_tos',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_for_hire',
            new_name='accepted_tos_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='download_link',
            new_name='links_download',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='download_location_link',
            new_name='links_download_location',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='full_url',
            new_name='links_followers_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='html_link',
            new_name='links_following_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='regular_url',
            new_name='links_html',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='raw_url',
            new_name='links_html_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='self_link',
            new_name='links_likes_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='small_s3_url',
            new_name='links_photos_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='small_url',
            new_name='links_portfolio_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_large_profile_image',
            new_name='links_self',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_medium_profile_image',
            new_name='links_self_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_small_profile_image',
            new_name='profile_image_large',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='thumb_url',
            new_name='profile_image_large_user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_total_collections',
            new_name='sponsor_followers',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_total_likes',
            new_name='sponsor_following',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_total_photos',
            new_name='sponsor_likes',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='sponsor_total_promoted_photos',
            new_name='total_collections',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='impression_urls',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='sponsor_instagram_username',
        ),
        migrations.AddField(
            model_name='photo',
            name='breadcrumbs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='for_hire',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='for_hire_user',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='instagram_username_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='profile_image_medium',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='profile_image_medium_user',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='profile_image_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='profile_image_small_user',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='social_instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='social_instagram_username_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='social_paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='social_paypal_email_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='social_portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='social_portfolio_url_user',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='social_twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='social_twitter_username_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_html',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_photos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor_self',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsorship_impression_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='topic_submissions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='total_collections_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='total_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='total_likes_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='total_photos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='total_photos_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='total_promoted_photos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='total_promoted_photos_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='urls_full',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='urls_raw',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='urls_regular',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='urls_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='urls_small_s3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='urls_thumb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='alt_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='current_user_collections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sponsor_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
