# Generated by Django 3.2 on 2024-01-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0007_auto_20240115_0644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='CreateAdsPhoto',
        ),
    ]
