# Generated by Django 3.2 on 2024-01-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0008_rename_photo_createadsphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createadsphoto',
            name='promoted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='sponsor_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='user_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
