# Generated by Django 3.2 on 2024-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0009_auto_20240115_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createadsphoto',
            name='sponsor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
