# Generated by Django 3.2 on 2024-01-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0010_alter_createadsphoto_sponsor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createadsphoto',
            name='sponsor_likes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
