# Generated by Django 3.2 on 2024-01-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_advertisement', '0011_alter_createadsphoto_sponsor_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createadsphoto',
            name='sponsor_followers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='sponsor_following',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='total_collections',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='total_collections_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='total_likes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='total_likes_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='total_photos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='total_photos_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='total_promoted_photos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='total_promoted_photos_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createadsphoto',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
