# Generated by Django 4.2.2 on 2023-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0002_documents_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='knowledge_base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documents',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
