# Generated by Django 4.2.2 on 2023-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0003_documents_dislike_documents_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='knowledge_base',
            field=models.BooleanField(default=False),
        ),
    ]
