# Generated by Django 4.2.2 on 2023-07-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0001_initial'),
        ('documentsData', '0011_alter_projects_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_id_for_document', to='projectsApp.projects'),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
