# Generated by Django 4.2.2 on 2023-08-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0002_workspace_admin_user_of_workspace_and_more'),
        ('documentsData', '0017_alter_documents_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='workspace_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_id_of_user_doc', to='team_members.workspace'),
        ),
    ]
