# Generated by Django 4.2.2 on 2023-08-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0018_documents_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='visible_by_workspace_member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
