# Generated by Django 3.2 on 2023-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0020_documents_editable_by_workspace_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='status',
            field=models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Draft', 'Draft'), ('Done', 'Done'), ('Pending', 'Pending'), ('Working', 'Working'), ('Urgent', 'Urgent')], default='Working', max_length=10, null=True),
        ),
    ]
