# Generated by Django 3.2 on 2023-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0021_documents_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_content',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
