# Generated by Django 4.2.2 on 2023-08-03 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateUniqueLinkForTeamMemberForInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_link_uuid', models.UUIDField(default=uuid.uuid4)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_admin_user', to=settings.AUTH_USER_MODEL)),
                ('invite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_user_from_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_or_not', models.BooleanField(blank=True, default=True, null=True)),
                ('unique_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_link', to='team_members.generateuniquelinkforteammemberforinvitation')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Workspace_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members', to='team_members.workspace')),
                ('team_member_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
