# Generated by Django 4.2.2 on 2023-08-03 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_members', '0002_workspace_admin_user_of_workspace_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='TeamMemberList',
        ),
        migrations.RemoveField(
            model_name='generateuniquelinkforteammemberforinvitation',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='generateuniquelinkforteammemberforinvitation',
            name='invite_user',
        ),
        migrations.AddField(
            model_name='generateuniquelinkforteammemberforinvitation',
            name='email',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
