# Generated by Django 4.2.2 on 2023-08-03 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0005_alter_generateuniquelinkforteammemberforinvitation_unique_link_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='unique_link',
        ),
        migrations.AddField(
            model_name='generateuniquelinkforteammemberforinvitation',
            name='workspace_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members_invitation_link', to='team_members.workspace'),
            preserve_default=False,
        ),
    ]
