# Generated by Django 4.2.2 on 2023-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0006_remove_workspace_unique_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberlist',
            name='admin_or_not',
            field=models.BooleanField(default=True),
        ),
    ]
