# Generated by Django 4.2.2 on 2023-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0009_teammemberlist_to_show_admin_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberlist',
            name='second_layer_admin_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
