# Generated by Django 4.2.2 on 2023-08-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_members', '0011_initialworkshopofuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialworkshopofuser',
            name='user_filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_filter_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
