# Generated by Django 4.2.2 on 2023-08-04 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_members', '0012_initialworkshopofuser_user_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialworkshopofuser',
            name='user_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_filter_id', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
