# Generated by Django 4.2.2 on 2023-08-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0013_alter_initialworkshopofuser_user_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateuniquelinkforteammemberforinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='initialworkshopofuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teammemberlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
