# Generated by Django 4.2.2 on 2023-08-08 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_members', '0014_generateuniquelinkforteammemberforinvitation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialworkshopofuser',
            name='owner_of_workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_owner_of_workspace', to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
