# Generated by Django 4.2.2 on 2023-08-08 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_members', '0015_initialworkshopofuser_owner_of_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialworkshopofuser',
            name='owner_of_workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner_of_workspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
