# Generated by Django 3.2 on 2023-08-30 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0017_alter_initialworkshopofuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberTeamNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_of_member', models.CharField(blank=True, default=3, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
