# Generated by Django 4.2.2 on 2023-06-21 04:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[accounts.models.validate_first_name]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[accounts.models.validate_last_name]),
        ),
    ]
