# Generated by Django 4.2.2 on 2023-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp_token_validation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_token',
            name='validation_count',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
