# Generated by Django 4.2.2 on 2023-06-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otp_token_validation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='auth_provider',
            field=models.CharField(blank=True, default='email', max_length=255, null=True),
        ),
    ]
