# Generated by Django 4.2.2 on 2023-07-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_general_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='General_Settings',
            new_name='GeneralSetting',
        ),
    ]
