# Generated by Django 4.2.4 on 2023-08-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_generate_word_restriction_for_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GENERATE_WORD_RESTRICTION_FOR_USER',
            new_name='GenerateWordRestrictionForUser',
        ),
    ]
