# Generated by Django 3.2 on 2023-08-16 17:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20230816_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
