# Generated by Django 3.2 on 2023-08-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_email_senemailtouser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SenEmailToUser',
            new_name='SendEmailToUser',
        ),
    ]
