# Generated by Django 3.2 on 2023-08-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_visitor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.TextField(default='Np'),
            preserve_default=False,
        ),
    ]
