# Generated by Django 3.2 on 2023-08-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20230820_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='region',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
