# Generated by Django 3.2 on 2023-09-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_otp_token_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp_token',
            options={'verbose_name_plural': 'User OTP Token'},
        ),
    ]
