# Generated by Django 3.2 on 2023-10-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_otp_token_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFromHubSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, null=True)),
                ('hubspot_user_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'UserFromHubSpot',
            },
        ),
    ]
