# Generated by Django 3.2 on 2023-08-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_openaitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAiToken_delete_it_after_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_generated', models.CharField(max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
