# Generated by Django 3.2 on 2023-08-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0017_alter_initialworkshopofuser_options'),
        ('template', '0003_openaitoken_delete_it_after_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleusertokengenerated',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_user_id', to='team_members.workspace'),
        ),
    ]
