# Generated by Django 3.2 on 2023-08-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0007_tokenofopenai'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenOfOpenAi',
            new_name='OpenAiToken',
        ),
    ]
