# Generated by Django 3.2 on 2023-08-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0008_rename_tokenofopenai_openaitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleusertokengenerated',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_id_used', to='template.template'),
        ),
    ]
