# Generated by Django 3.2 on 2023-09-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0053_tempvideodetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempvideodetails',
            name='directory_of_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
