# Generated by Django 3.2 on 2023-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0054_tempvideodetails_directory_of_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempvideodetails',
            name='scripts_of_audio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
