# Generated by Django 3.2 on 2023-10-01 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_members', '0020_alter_teammemberteamnumber_no_of_member'),
        ('template', '0056_tempvideodetails_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribeSpeechModal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scripts_of_audio', models.TextField(blank=True, null=True)),
                ('answer_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcribe_user_id', to=settings.AUTH_USER_MODEL)),
                ('workspace_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_id_transcribe_user', to='team_members.workspace')),
            ],
        ),
    ]
