# Generated by Django 3.2 on 2023-10-19 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0021_alter_teammemberteamnumber_no_of_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatapicontentmodel',
            name='workspace_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_api_content_workspace_id', to='team_members.workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatapicontentmodel',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatapicontentmodel',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatapicontentmodel',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatapicontentmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_api_content_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
