# Generated by Django 4.2.2 on 2023-07-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandvoice',
            name='brand_voice',
            field=models.TextField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='brandvoice',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandvoice',
            name='content_summarize',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
