# Generated by Django 4.2.2 on 2023-07-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_voice', '0003_brandvoice_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandvoice',
            name='brand_voice',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
