# Generated by Django 4.2.2 on 2023-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_voice', '0002_alter_brandvoice_brand_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandvoice',
            name='trash',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
