# Generated by Django 4.2.2 on 2023-07-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_starter', models.TextField(max_length=40)),
                ('monthly_boss_mode', models.TextField(max_length=40)),
                ('annaully_starter', models.TextField(max_length=40)),
                ('annaully_boss_mode', models.TextField(max_length=40)),
            ],
        ),
    ]
