# Generated by Django 4.2.2 on 2023-07-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionmoney_annaully_boss_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'starter'), ('boss', 'boss'), ('enterprise', 'enterprise')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
