# Generated by Django 4.2.2 on 2023-07-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_trail_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trail_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
