# Generated by Django 3.2 on 2023-08-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_teammemberprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammemberprice',
            options={'verbose_name_plural': 'Price of Seat'},
        ),
    ]
