# Generated by Django 3.2 on 2023-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_teammemberprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_team_stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
