# Generated by Django 3.2 on 2023-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_auto_20230907_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterprisePlanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Why Enterprise',
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Why Enterprise',
            },
        ),
        migrations.CreateModel(
            name='YearlyPlanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Why Yearly',
            },
        ),
    ]
