# Generated by Django 4.2.2 on 2023-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0003_rename_teammember_teammemberlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberlist',
            name='admin_or_not',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
