# Generated by Django 4.2.2 on 2023-08-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0004_teammemberlist_admin_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateuniquelinkforteammemberforinvitation',
            name='unique_link_uuid',
            field=models.CharField(max_length=400),
        ),
    ]
