# Generated by Django 4.2.2 on 2023-08-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0007_alter_teammemberlist_admin_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberlist',
            name='workspace_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
