# Generated by Django 4.2.2 on 2023-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0008_teammemberlist_workspace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberlist',
            name='to_show_admin_user_email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
