# Generated by Django 3.2 on 2023-08-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0016_alter_initialworkshopofuser_owner_of_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialworkshopofuser',
            options={'verbose_name_plural': 'Add Workspace'},
        ),
    ]
