# Generated by Django 3.2 on 2023-08-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0018_teammemberteamnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammemberteamnumber',
            options={'verbose_name_plural': 'Team Member Number'},
        ),
        migrations.AddField(
            model_name='teammemberteamnumber',
            name='Workspace_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members_team_number', to='team_members.workspace'),
        ),
    ]
