# Generated by Django 3.2 on 2023-08-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0019_auto_20230830_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberteamnumber',
            name='no_of_member',
            field=models.CharField(blank=True, default=2, max_length=40, null=True),
        ),
    ]
