# Generated by Django 3.2 on 2023-08-26 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
                ('premium', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('pre_define_value', models.TextField(blank=True, null=True)),
                ('component', models.CharField(choices=[('text', 'text'), ('textarea', 'textarea'), ('select', 'select'), ('Example', 'Example')], max_length=20)),
                ('type_field', models.CharField(choices=[('string', 'string')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(max_length=100)),
                ('range_of_text', models.PositiveIntegerField()),
                ('maxLength', models.PositiveIntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomTemplateIdTemplateField', to='custome_template.customtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleKeyFeatureValueByCustomCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('inner_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExampleKeyFeatureValueByCustomCustomerTemplateId', to='custome_template.customtemplatefield')),
                ('outer_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExampleCustomTemplate', to='custome_template.customtemplate')),
            ],
        ),
    ]
