# Generated by Django 3.2 on 2023-08-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custome_template', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplate',
            name='template_taken_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_belongs_to', to='template.template'),
        ),
        migrations.AddField(
            model_name='customtemplate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_add_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
