# Generated by Django 3.2 on 2023-10-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custome_template', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplate',
            name='what_to_generate',
            field=models.TextField(default=''),
        ),
    ]
