# Generated by Django 4.2.2 on 2023-07-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
