# Generated by Django 4.2.2 on 2023-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0004_alter_documents_knowledge_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='dislike',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='knowledge_base',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
