# Generated by Django 4.2.2 on 2023-07-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0005_alter_documents_created_at_alter_documents_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='trash',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
