# Generated by Django 4.2.2 on 2023-07-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0007_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='trash',
        ),
        migrations.AddField(
            model_name='documents',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_id_for_document', to='documentsData.projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='publish',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
