# Generated by Django 4.2.2 on 2023-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0008_remove_projects_trash_documents_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
