# Generated by Django 4.2.2 on 2023-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0010_alter_projects_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
