# Generated by Django 3.2 on 2023-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsData', '0022_alter_documents_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Draft', 'Draft'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Working', 'Working'), ('Urgent', 'Urgent')], default='Working', max_length=10, null=True),
        ),
    ]
