# Generated by Django 4.2.2 on 2023-06-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_token',
            name='validation_count',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
