# Generated by Django 4.2.2 on 2023-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraccount_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
