# Generated by Django 3.2 on 2023-08-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_generate_word_restriction_for_user_generatewordrestrictionforuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatewordrestrictionforuser',
            name='words',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
