# Generated by Django 3.2 on 2023-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_generatewordrestrictionforuser_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('recipient', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='generatewordrestrictionforuser',
            options={'verbose_name_plural': 'User Limitation'},
        ),
    ]
