# Generated by Django 3.2 on 2023-08-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_email_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='SenEmailToUser',
        ),
    ]
