# Generated by Django 3.2 on 2023-08-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='count',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
