# Generated by Django 3.2 on 2023-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_visitor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='latitude',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='longitude',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
