# Generated by Django 3.2 on 2023-08-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_visitor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
