# Generated by Django 3.2 on 2023-08-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_visitor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatewordrestrictionforuser',
            name='words',
            field=models.TextField(default=0),
        ),
    ]
