# Generated by Django 3.2 on 2023-08-28 03:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_generatewordrestrictionforuser_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[accounts.models.validate_first_name]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[accounts.models.validate_last_name]),
        ),
    ]
