# Generated by Django 3.2 on 2023-09-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20230828_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
