# Generated by Django 3.2 on 2023-10-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_userfromhubspot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfromhubspot',
            options={'verbose_name_plural': 'User From HubSpot'},
        ),
        migrations.AlterField(
            model_name='userfromhubspot',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
