# Generated by Django 3.2 on 2023-08-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('premium', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ManyToManyField(to='template.Categorie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_by_user_workflow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WorkFlow Template',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowSteps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('step_title', models.CharField(blank=True, max_length=80, null=True)),
                ('step_no', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('WorkFlowTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkFlowTemplateId', to='workflow.workflowtemplate')),
            ],
            options={
                'verbose_name_plural': 'WorkFlow Steps',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_title', models.CharField(blank=True, max_length=100, null=True)),
                ('step_no', models.CharField(max_length=80)),
                ('pre_define_value', models.TextField(blank=True, null=True)),
                ('component', models.CharField(choices=[('textarea', 'textarea'), ('select', 'select')], max_length=20)),
                ('type_field', models.CharField(choices=[('string', 'string')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(max_length=100)),
                ('range_of_text', models.PositiveIntegerField()),
                ('maxLength', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('WorkFlow_Steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkFlowStepsId', to='workflow.workflowsteps')),
            ],
            options={
                'verbose_name_plural': 'WorkFlow Fields',
            },
        ),
    ]
