# Generated by Django 4.2.2 on 2023-07-21 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattemplatemodel',
            old_name='content',
            new_name='description',
        ),
        migrations.CreateModel(
            name='ChatFirstStepTemplateModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_first_step_template_name', models.TextField(blank=True, max_length=70, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trash', models.BooleanField(blank=True, default=False, null=True)),
                ('chat_template_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_template_model_id', to='chat_template.chattemplatemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
