# Generated by Django 4.2.2 on 2023-07-21 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat_template', '0002_rename_content_chattemplatemodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatValueOfTemplateModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_of_prompt', models.TextField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trash', models.BooleanField(blank=True, default=False, null=True)),
                ('chat_template_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_first_step_template_id', to='chat_template.chatfirststeptemplatemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
