# Generated by Django 4.2.2 on 2023-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_template', '0005_customechattemplateofuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customechattemplateofuser',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customechattemplateofuser',
            name='title',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
