# Generated by Django 3.2 on 2023-10-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_template', '0006_alter_customechattemplateofuser_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatfirsttemplatemodel',
            options={'verbose_name_plural': 'Chat Template'},
        ),
        migrations.AlterModelOptions(
            name='chatsecondsteptemplatemodel',
            options={'verbose_name_plural': 'Chat Fields Template'},
        ),
        migrations.AlterModelOptions(
            name='chatthirdvalueoftemplatemodel',
            options={'verbose_name_plural': 'Chat Template Value '},
        ),
    ]
