from django.db import models
import uuid

class CreateAdsPhoto(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.SlugField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    updated_at = models.DateTimeField(auto_now=True,null=True,blank=True)
    promoted_at = models.DateTimeField(auto_now=True,null=True, blank=True)
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    color = models.CharField(max_length=255,null=True, blank=True)
    blur_hash = models.CharField(max_length=255,null=True, blank=True)
    description = models.TextField(null=True,blank=True)
    alt_description = models.TextField(null=True, blank=True)
    breadcrumbs = models.CharField(max_length=255, null=True, blank=True)
    urls_raw = models.URLField(null=True, blank=True)
    urls_full = models.URLField(null=True, blank=True)
    urls_regular = models.URLField(null=True, blank=True)
    urls_small = models.URLField(null=True, blank=True)
    urls_thumb = models.URLField(null=True, blank=True)
    urls_small_s3 = models.URLField(null=True, blank=True)

    links_self = models.URLField(null=True, blank=True)
    links_html = models.URLField(null=True, blank=True)
    links_download = models.URLField(null=True, blank=True)
    links_download_location = models.URLField(null=True, blank=True)

    likes = models.IntegerField(null=True, blank=True)
    liked_by_user = models.BooleanField(null=True, blank=True)
    current_user_collections = models.JSONField(null=True, blank=True)
    sponsorship_impression_urls = models.JSONField(null=True, blank=True)

    tagline = models.TextField(null=True, blank=True)
    tagline_url = models.URLField(null=True, blank=True)

    sponsor_id =  models.CharField(max_length=255, null=True, blank=True)
    sponsor_updated_at = models.DateTimeField(auto_now=True,null=True, blank=True)

    sponsor_username = models.CharField(max_length=255, null=True, blank=True)
    sponsor_name = models.CharField(max_length=255, null=True, blank=True)
    sponsor_first_name = models.CharField(max_length=255, null=True, blank=True)
    sponsor_last_name = models.CharField(max_length=255, null=True, blank=True)
    sponsor_twitter_username = models.CharField(max_length=255, null=True, blank=True)
    sponsor_portfolio_url = models.URLField(null=True, blank=True)
    sponsor_bio = models.TextField(null=True, blank=True)
    sponsor_location = models.CharField(max_length=255, null=True, blank=True)
    sponsor_links = models.JSONField(null=True, blank=True)
    sponsor_self = models.URLField(null=True, blank=True)
    sponsor_html = models.URLField(null=True, blank=True)
    sponsor_photos = models.JSONField(null=True, blank=True)
    sponsor_likes = models.CharField(max_length=10,null=True, blank=True)
    sponsor_portfolio = models.URLField(null=True, blank=True)
    sponsor_following = models.CharField(max_length=50,null=True, blank=True)
    sponsor_followers = models.CharField(max_length=50,null=True, blank=True)

    profile_image_small = models.URLField(null=True, blank=True)
    profile_image_medium = models.URLField(null=True, blank=True)
    profile_image_large = models.URLField(null=True, blank=True)

    instagram_username = models.CharField(max_length=255, null=True, blank=True)
    total_collections = models.CharField(max_length=50,null=True, blank=True)
    total_likes = models.CharField(max_length=50,null=True, blank=True)
    total_photos = models.CharField(max_length=50,null=True, blank=True)
    total_promoted_photos = models.CharField(max_length=50,null=True, blank=True)
    accepted_tos = models.BooleanField(null=True, blank=True)
    for_hire = models.BooleanField(null=True, blank=True)

    social_instagram_username = models.CharField(max_length=255, null=True, blank=True)
    social_portfolio_url = models.URLField(null=True, blank=True)
    social_twitter_username = models.CharField(max_length=255, null=True, blank=True)
    social_paypal_email = models.EmailField(null=True, blank=True)

    topic_submissions = models.JSONField(null=True, blank=True)

    user_id = models.CharField(max_length=50,null=True, blank=True)
    user_updated_at = models.DateTimeField(auto_now=True,null=True,blank=True)
    user_username = models.CharField(max_length=255,null=True, blank=True)
    user_name = models.CharField(max_length=255,null=True, blank=True)
    user_first_name = models.CharField(max_length=255, null=True, blank=True)
    user_last_name = models.CharField(max_length=255, null=True, blank=True)
    user_twitter_username = models.CharField(max_length=255, null=True, blank=True)
    user_portfolio_url = models.URLField(null=True, blank=True)
    user_bio = models.TextField(null=True, blank=True)
    user_location = models.CharField(max_length=255, null=True, blank=True)

    links_self_user = models.URLField(null=True, blank=True)
    links_html_user = models.URLField(null=True, blank=True)
    links_photos_user = models.URLField(null=True, blank=True)
    links_likes_user = models.URLField(null=True, blank=True)
    links_portfolio_user = models.URLField(null=True, blank=True)
    links_following_user = models.URLField(null=True, blank=True)
    links_followers_user = models.URLField(null=True, blank=True)

    profile_image_small_user = models.URLField(null=True, blank=True)
    profile_image_medium_user = models.URLField(null=True, blank=True)
    profile_image_large_user = models.URLField(null=True, blank=True)

    instagram_username_user = models.CharField(max_length=255, null=True, blank=True)
    total_collections_user = models.CharField(max_length=50,null=True, blank=True)
    total_likes_user = models.CharField(max_length=50,null=True, blank=True)
    total_photos_user = models.CharField(max_length=50,null=True, blank=True)
    total_promoted_photos_user = models.CharField(max_length=50,null=True, blank=True)
    accepted_tos_user = models.BooleanField(null=True, blank=True)
    for_hire_user = models.BooleanField(null=True, blank=True)

    social_instagram_username_user = models.CharField(max_length=255, null=True, blank=True)
    social_portfolio_url_user = models.URLField(null=True, blank=True)
    social_twitter_username_user = models.CharField(max_length=255, null=True, blank=True)
    social_paypal_email_user = models.EmailField(null=True, blank=True)

    def __str__(self):
        return str(self.id)
